version: 2.1

orbs:
  codecov: codecov/codecov@3

executors:
  linux:
    docker:
      - image: cimg/openjdk:17.0-browsers

jobs:
  upload-coverage:
    executor: linux
    steps:
      - checkout
      - run:
          command: Xvfb :99 -screen 0 1280x1024x24
          background: true
      - run: ./gradlew test koverXmlReport
      - codecov/upload

workflows:
  build:
    jobs:
      - upload-coverage
