const val KTFX_COMMONS = "$RELEASE_ARTIFACT-commons"
const val KTFX_COROUTINES = "$RELEASE_ARTIFACT-coroutines"
const val KTFX_LAYOUTS = "$RELEASE_ARTIFACT-layouts"
const val KTFX_LISTENERS = "$RELEASE_ARTIFACT-listeners"
const val KTFX_STYLES = "$RELEASE_ARTIFACT-styles"

val KTFX_ARTIFACTS = listOf(RELEASE_ARTIFACT, KTFX_COMMONS, KTFX_COROUTINES, KTFX_LAYOUTS, KTFX_LISTENERS, KTFX_STYLES)

const val KTFX_LAYOUTS_CONTROLSFX = "$KTFX_LAYOUTS-controlsfx"

val KTFX_THIRDPARTY_ARTIFACTS = listOf(KTFX_LAYOUTS_CONTROLSFX)

fun String.asGroup(): String = replace('-', '.')