const val releaseUser = "hendraanggrian"
const val releaseArtifact = "kfx"
const val releaseGroup = "com.$releaseUser.$releaseArtifact"
const val releaseVersion = "0.1.2"
const val releaseDesc = "Kotlin extensions for JavaFX app development and more"
const val releaseWeb = "https://github.com/$releaseUser/$releaseArtifact"