const val releaseUser = "hendraanggrian"
const val releaseArtifact = "ktfx"
const val releaseGroup = "com.$releaseUser.$releaseArtifact"
const val releaseVersion = "0.2.3"
const val releaseDesc = "Kotlin extensions for JavaFX app development and more"
const val releaseWeb = "https://github.com/$releaseUser/$releaseArtifact"