const val VERSION_GRADLE = "4.9"
const val VERSION_KOTLIN = "1.2.60"
const val VERSION_COROUTINES = "0.24.0"

internal const val VERSION_CONTROLSFX = "8.40.14"
internal const val VERSION_JFOENIX = "8.0.4"

internal const val VERSION_DOKKA = "0.9.17"
internal const val VERSION_TESTFX = "4.0.13-alpha"
internal const val VERSION_TRUTH = "0.41"
internal const val VERSION_JUNIT = "4.12"
internal const val VERSION_BINTRAY = "1.8.4"
internal const val VERSION_BINTRAY_RELEASE = "0.8.1"
internal const val VERSION_GIT_PUBLISH = "0.3.3"
internal const val VERSION_KTLINT = "0.27.0"