const val VERSION_GRADLE = "5.2.1"
const val VERSION_KOTLIN = "1.3.21"
const val VERSION_COROUTINES = "1.1.1"

internal const val VERSION_CONTROLSFX = "8.40.14"
internal const val VERSION_JFOENIX = "8.0.7"

internal const val VERSION_DOKKA = "0.9.17"
internal const val VERSION_TESTFX = "4.0.15-alpha"
internal const val VERSION_TRUTH = "0.43"
internal const val VERSION_JUNIT = "4.12"
internal const val VERSION_BINTRAY = "1.8.4"
internal const val VERSION_BINTRAY_RELEASE = "0.9"
internal const val VERSION_GIT_PUBLISH = "0.3.3"
internal const val VERSION_KTLINT = "0.30.0"