const val VERSION_GRADLE = "4.6"
const val VERSION_KOTLIN = "1.2.31"
const val VERSION_COROUTINES = "0.22.5"

internal const val VERSION_DOKKA = "0.9.16"
internal const val VERSION_SPEK = "1.1.5"
internal const val VERSION_JUNIT_PLATFORM = "1.0.0"
internal const val VERSION_TESTFX = "4.0.13-alpha"
internal const val VERSION_TRUTH = "0.39"
internal const val VERSION_BINTRAY_RELEASE = "0.8.1"
internal const val VERSION_GIT_PUBLISH = "0.3.3"
internal const val VERSION_KTLINT = "0.21.0"