var pages = [{'name': 'fun JFXDecorator.onCloseButtonAction(context: CoroutineContext, action: SuspendFunction1<CoroutineScope, Unit>)', 'description':'ktfx.jfoenix.coroutines.onCloseButtonAction', 'location':'ktfx-jfoenix-coroutines/ktfx.jfoenix.coroutines/on-close-button-action.html', 'searchKey':'onCloseButtonAction'},
{'name': 'fun JFXDialog.onDialogClosed(context: CoroutineContext, action: SuspendFunction2<CoroutineScope, JFXDialogEvent, Unit>)', 'description':'ktfx.jfoenix.coroutines.onDialogClosed', 'location':'ktfx-jfoenix-coroutines/ktfx.jfoenix.coroutines/on-dialog-closed.html', 'searchKey':'onDialogClosed'},
{'name': 'fun JFXDialog.onDialogOpened(context: CoroutineContext, action: SuspendFunction2<CoroutineScope, JFXDialogEvent, Unit>)', 'description':'ktfx.jfoenix.coroutines.onDialogOpened', 'location':'ktfx-jfoenix-coroutines/ktfx.jfoenix.coroutines/on-dialog-opened.html', 'searchKey':'onDialogOpened'},
{'name': 'fun JFXDrawer.onDrawerClosed(context: CoroutineContext, action: SuspendFunction2<CoroutineScope, JFXDrawerEvent, Unit>)', 'description':'ktfx.jfoenix.coroutines.onDrawerClosed', 'location':'ktfx-jfoenix-coroutines/ktfx.jfoenix.coroutines/on-drawer-closed.html', 'searchKey':'onDrawerClosed'},
{'name': 'fun JFXDrawer.onDrawerClosing(context: CoroutineContext, action: SuspendFunction2<CoroutineScope, JFXDrawerEvent, Unit>)', 'description':'ktfx.jfoenix.coroutines.onDrawerClosing', 'location':'ktfx-jfoenix-coroutines/ktfx.jfoenix.coroutines/on-drawer-closing.html', 'searchKey':'onDrawerClosing'},
{'name': 'fun JFXDrawer.onDrawerOpened(context: CoroutineContext, action: SuspendFunction2<CoroutineScope, JFXDrawerEvent, Unit>)', 'description':'ktfx.jfoenix.coroutines.onDrawerOpened', 'location':'ktfx-jfoenix-coroutines/ktfx.jfoenix.coroutines/on-drawer-opened.html', 'searchKey':'onDrawerOpened'},
{'name': 'fun JFXDrawer.onDrawerOpening(context: CoroutineContext, action: SuspendFunction2<CoroutineScope, JFXDrawerEvent, Unit>)', 'description':'ktfx.jfoenix.coroutines.onDrawerOpening', 'location':'ktfx-jfoenix-coroutines/ktfx.jfoenix.coroutines/on-drawer-opening.html', 'searchKey':'onDrawerOpening'},
{'name': 'fun JFXAnimationTimer.onFinished(context: CoroutineContext, action: SuspendFunction1<CoroutineScope, Unit>)', 'description':'ktfx.jfoenix.coroutines.onFinished', 'location':'ktfx-jfoenix-coroutines/ktfx.jfoenix.coroutines/on-finished.html', 'searchKey':'onFinished'},
{'name': 'fun <T> JFXAutoCompletePopup<T>.selectionHandler(context: CoroutineContext, action: SuspendFunction2<CoroutineScope, JFXAutoCompleteEvent<T>, Unit>)', 'description':'ktfx.jfoenix.coroutines.selectionHandler', 'location':'ktfx-jfoenix-coroutines/ktfx.jfoenix.coroutines/selection-handler.html', 'searchKey':'selectionHandler'}]
